name: Telegram Face Bot
version: "0.1.13"
slug: telegram_face_bot
description: Telegram bot that learns and recognizes faces from photos
url: https://github.com/hilayc/telegram-face-bot
arch:
  - amd64
image: hilayc9/telegram-face-bot
startup: application
boot: auto
init: false
host_network: true
map:
  - type: addon_config
    read_only: false
options:
  TELEGRAM_BOT_API_TOKEN: ""
  FACE_MATCH_TOLERANCE: "0.45"
  FACE_DETECTION_MODEL: "hog"
  FACE_TRAIN_JITTERS: "2"
  FACE_FIND_JITTERS: "1"
  FACE_USE_MEAN_ENCODING: "true"
schema:
  TELEGRAM_BOT_API_TOKEN: str
  FACE_MATCH_TOLERANCE: float
  FACE_DETECTION_MODEL: str
  FACE_TRAIN_JITTERS: int
  FACE_FIND_JITTERS: int
  FACE_USE_MEAN_ENCODING: str