name: Telegram Face Bot
version: "0.1.3"
slug: telegram_face_bot
description: Telegram bot that learns and recognizes faces from photos
url: https://github.com/hilayc/telegram-face-bot
arch:
  - amd64
image: hilayc9/telegram-face-bot
startup: application
boot: auto
init: false
host_network: true
map:
  - share:rw
  - config:rw
  - ssl:ro
options:
  TELEGRAM_BOT_API_TOKEN: ""
schema:
  TELEGRAM_BOT_API_TOKEN: str

